package com.likeminds.likemindschat.conversation.model

enum class ConversationState(val value: Int) {
    NORMAL(0),
    FIRST_CONVERSATION(1),
    MEMBER_JOINED_OPEN_CHATROOM(2),
    MEMBER_LEFT_OPEN_CHATROOM(3),
    COMMUNITY_PURPOSE_EDITED(5),
    GUEST_USER_FOLLOWED(6),
    MEMBER_ADDED_TO_CHATROOM(7),
    MEMBER_LEFT_SECRET_CHATROOM(8),
    MEMBER_REMOVED_FROM_CHATROOM(9),
    POLL(10),
    ALL_MEMBERS_ADDED(11),
    TOPIC_CHANGED(12),
    DM_MEMBER_REMOVED_LEFT(13),
    DM_CM_BECOMES_MEMBER_DISABLE(14),
    DM_MEMBER_BECOME_CM(15),
    DM_CM_BECOMES_MEMBER_ENABLE(16),
    DM_MEMBER_BECOMES_CM_ENABLE(17),
    DM_REQUEST_REJECTED(19),
    DM_REQUEST_ACCEPTED(20)
}