dependencies {
    //android core
    implementation deps.android_core.core
    implementation deps.android_core.appcompat

    //internal sdk
    implementation deps.internal.sdk

    //dagger
    implementation deps.dagger.main
    kapt deps.dagger.compiler

    //workmanager
    api deps.workmanager.main

    //firebase
    api platform(deps.firebase.bom)
    api deps.firebase.database
    api deps.firebase.messaging

    //retrofit gson
    implementation deps.retrofit.gson

    //testing
    testImplementation deps.testing.junit
    androidTestImplementation deps.testing.android_junit
    androidTestImplementation deps.testing.espresso
}